### ISSUE TITLE
Page won't be as narrow as the window

### ISSUE THREAD

**Issue by eloekset** [eloekset/UWPSplitViewIssue#1]
The issue I experience using the UWP SplitView control is that the Width of a Page hosted inside the SplitView.Content Frame stops shrinking below a certain limit.
![2016-03-21_21-40-33](https://cloud.githubusercontent.com/assets/791721/13934050/569ccf4c-efb0-11e5-8d52-b192c7106ece.png)

By using `SetPreferredMinSize(new Size(200, 300))` the window can shrink to that size, but the page itself stops at 320 by 264.
![2016-03-21_22-02-54](https://cloud.githubusercontent.com/assets/791721/13934175/f7da6586-efb0-11e5-8e7d-92da27eb3e1a.png)

I try to develop a calculator looking a lot like the built-in one in Windows 10, but I'm not able to make it as small as the original, which can be 202 by 357 pixels.
![2016-03-21_22-06-45](https://cloud.githubusercontent.com/assets/791721/13934267/927393c4-efb1-11e5-8c5c-21e1d8504e06.png)
![2016-03-21_22-10-06](https://cloud.githubusercontent.com/assets/791721/13934301/c7b845fc-efb1-11e5-951c-129d451ab345.png)

My implementation has the same problem as this sample project, shown by the text "Some page", which isn't centered because the page content is wider than the window.

**Comment by eloekset** [comment]
I've also posted a question at StackOverflow pointing to this issue: http://stackoverflow.com/questions/36142054/page-inside-uwp-splitview-control-has-a-limit-to-its-width

**Comment by LanceMcCarthy** [comment]
I've answered the StackOverflow question, here is a screenshot of the result on top of the Debug Output:

![2016-03-21_1916](https://cloud.githubusercontent.com/assets/3520532/13937201/8b81d0ca-ef99-11e5-8002-08228bd9861b.png)

**Comment by eloekset** [comment]
Thanks a lot @LanceMcCarthy! 
Setting SplitView.OpenPaneLength="200" was perfect for the calculator app.

![2016-03-22_19-55-10](https://cloud.githubusercontent.com/assets/791721/13964109/81381aaa-f068-11e5-9101-909eb529beda.png)

I've updated this sample project by applying your snippets at StackOverflow.
